export type Profile = {
  familyNameKanji: string,
  givenNameKanji: string,
  familyNameKana: string,
  givenNameKana: string,
  familyNameEn: string,
  givenNameEn: string,
  fullNameKanji: string,
  fullNameKana: string,
  fullNameEn: string,
  nickname: string,
  job: string,
  email: string,
  bio: string,
  location: string,
  profileImageUrl: string,
}
